fix: trailing comma makes json invalid
liyasthomas/postwoman pull request #4416
Opened 2024-10-08 12:43 UTC by anwarulislam

Closes #4411 

### What's changed
This pull request fixes an issue where a trailing comma in a JSON object was causing the JSON to be invalid. This was leading to errors when the JSON was being parsed.
The fix involves removing the trailing comma, ensuring the JSON is correctly formatted and valid.

- [ ] Not Completed
- [x] Completed

### Notes to reviewers
#### Examples JSON body
```
{
  // https://hello.com/
  "id": "https://hello.com",
  "value": {
    "num": 2,
  },
}
```

2024-10-08 14:01 UTC, Pranay-Pandey commented
Hello, just wondering 
Can this be solved by removing the DEFAULT_OPTIONS for formatting in the file 

`packages/hoppscotch-common/src/helpers/editor/linting/jsoncPretty.ts`

```
const DEFAULT_OPTIONS: Required<PrettifyOptions> = {
  indent: 2,
  maxLength: 80,
  commentSpace: true,
  trailingComma: true,
}
```

2024-10-08 14:45 UTC, anwarulislam commented
Hi, @Pranay-Pandey!
So, it wasn't really about how JSON looks on the client side, or even how it's formatted with those trailing commas. The problem was actually on the server side – the JSON was invalid because trailing commas were not being removed before sending the request.

2024-10-10 06:24 UTC, jamesgeorge007 requested changes
Comments appearing towards the end are stripped with the `Pretiffy` action.

  https://github.com/user-attachments/assets/11d987d0-20d4-488d-95f7-0331759c7a5b

2024-10-11 11:27 UTC, jamesgeorge007 submitted a review, later dismissed

2024-10-22 16:57 UTC, jamesgeorge007 approved these changes

2024-10-24 16:11 UTC, nivedin approved these changes

2024-10-28 15:33 UTC, AndrewBastin approved these changes

2024-10-28 15:34 UTC, merged